name: flutter_clean_price_tracker
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  get_it: ^7.2.0
  equatable: ^2.0.5
  freezed: ^2.3.2
  injectable: ^2.1.0
  json_serializable: ^6.5.4
  web_socket_channel: ^2.3.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
